/**
 * Product       : Hiperium Project
 * Lead Architect: Andres Solorzano.
 * Created date  : 08-05-2009 23:30:00
 * 
 * The contents of this file are copyrighted by Andres Solorzano 
 * and it is protected by the license: "GPL V3." You can find a copy of this 
 * license at: http://www.hiperium.com/about/licence.html
 * 
 * Copyright 2014. All rights reserved.
 * 
 */
package com.hiperium.security.aurora.bootstrap.function.exception;

import java.io.Serializable;


/**
 * This is a subclass of Exception class that implements the properties
 * to manage errors generated by services.
 * 
 * @author Andres Solorzano.
 * 
 */
public class HiperiumFunctionException extends Exception implements Serializable {

	private static final long serialVersionUID = -2497389416820959668L;

	public HiperiumFunctionException() {
		super();
	}

	public HiperiumFunctionException(String message) {
		super(message);
	}
	

	public HiperiumFunctionException(String message, Throwable cause) {
		super(message, cause);
	}

}
